import {
  BookCheck,
  CalendarCheck,
  ClipboardList,
  FileSpreadsheet,
  FolderKanban,
  Gamepad2,
  Goal,
  GraduationCap,
  HandCoins,
  House,
  IdCard,
  ListChecks,
  Network,
  ShieldCheck,
  Trophy,
  Users,
} from 'lucide-react'

export const navItems = [
  { title: 'Home', href: '/', icon: House },
  { title: 'Standards', href: '/standards', icon: ShieldCheck },
  { title: 'Team Info', href: '/team-info', icon: IdCard },
  { title: 'Roster', href: '/roster', icon: Users },
  { title: 'Player Profiles', href: '/player-profiles', icon: GraduationCap },
  { title: 'Practice Planning', href: '/practice-planning', icon: ClipboardList },
  { title: 'NCS Roster Dashboard', href: '/ncs-roster-dashboard', icon: BookCheck },
  { title: 'NCS Change Review', href: '/ncs-change-review', icon: ListChecks },
  { title: 'NCS Tournament Tracker', href: '/ncs-tournament-tracker', icon: Trophy },
  { title: 'Integrations Hub', href: '/integrations-hub', icon: Network },
  { title: 'GameChanger', href: '/gamechanger', icon: Gamepad2 },
  { title: 'Coach', href: '/coach', icon: Goal },
  { title: 'Player Development', href: '/player-development', icon: CalendarCheck },
  { title: 'Teams', href: '/teams', icon: FolderKanban },
  { title: 'Social Media Hub', href: '/social-media-hub', icon: FileSpreadsheet },
  { title: 'Fundraising', href: '/fundraising', icon: HandCoins },
] as const
